--[[ StatCoachData_Mists.lua
     MISTS OF PANDARIA CLASSIC data (5.5.x, level 90). Loaded only by StatCoach_Mists.toc.
     Pure tables, no API calls. GENERATED by Tools/build_mists_data.py from the harvest in
     CoachProbe/mists_stats (2026-09-24) - edit the harvest and rebuild, not this file.

     The caps are NOT in here: the engine reads them from the game (see the MISTS path
     in StatCoach.lua). This file carries, per specialization, the order of the stats on
     Wowhead's Mists of Pandaria Classic stat priority page, what the spec attacks with
     (which caps apply), and the guide's notes.
]]--

local ADDON, ns = ...
ns.Data = ns.Data or {}
local D = ns.Data

D.mists = D.mists or {}
local M = D.mists

-- Hit and expertise rating per 1% at level 90, as the guides state it (6 of them agree).
-- Only used when the character has no hit or expertise rating to read the ratio from.
M.RATING_PER_PCT = 340

-- Specialization id -> the English key below. Ids are language-independent.
M.SPECID = {
  [62] = "Arcane",
  [63] = "Fire",
  [64] = "Frost",
  [65] = "Holy",
  [66] = "Protection",
  [70] = "Retribution",
  [71] = "Arms",
  [72] = "Fury",
  [73] = "Protection",
  [102] = "Balance",
  [103] = "Feral",
  [104] = "Guardian",
  [105] = "Restoration",
  [250] = "Blood",
  [251] = "Frost",
  [252] = "Unholy",
  [253] = "Beast Mastery",
  [254] = "Marksmanship",
  [255] = "Survival",
  [256] = "Discipline",
  [257] = "Holy",
  [258] = "Shadow",
  [259] = "Assassination",
  [260] = "Combat",
  [261] = "Subtlety",
  [262] = "Elemental",
  [263] = "Enhancement",
  [264] = "Restoration",
  [265] = "Affliction",
  [266] = "Demonology",
  [267] = "Destruction",
  [268] = "Brewmaster",
  [269] = "Windwalker",
  [270] = "Mistweaver",
}

M.classOrder = { "WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "DEATHKNIGHT", "SHAMAN", "MAGE", "WARLOCK", "MONK", "DRUID" }

M.classes = {
  WARRIOR = {
    specOrder = { "Arms", "Fury", "Protection" },
    specs = {
      Arms = {
        role = "DAMAGER", primary = "Strength", attack = "melee",
        stats = { "Hit", "Expertise", "Strength", "Crit", "Mastery", "Haste" },
        notes = "Hit and expertise to 7.5% each, then strength, crit, mastery and haste.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Arms Warrior guide, 2026/06/29.",
      },
      Fury = {
        role = "DAMAGER", primary = "Strength", attack = "melee",
        stats = { "Hit", "Expertise", "Strength", "Crit", "Mastery", "Haste" },
        notes = "Hit and expertise to 7.5% each, then strength, crit, mastery and haste. White swings keep missing up to 26.5% hit while dual wielding - worth the least of all.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Fury Warrior guide, 2026/06/05.",
      },
      Protection = {
        role = "TANK", primary = "Strength", attack = "melee",
        stats = { "Stamina", "Hit", "Expertise", "Parry", "Strength", "Dodge", "Mastery", "Crit", "Haste" },
        notes = "Stamina first, then hit to 7.5% and expertise to 15%, then parry and strength. Other setups reshuffle what comes after the caps; the caps stay near the top.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Protection Warrior guide, 2026/06/29.",
      },
    },
  },
  PALADIN = {
    specOrder = { "Holy", "Protection", "Retribution" },
    specs = {
      Holy = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Spirit", "Intellect", "Mastery", "Crit", "Haste" },
        notes = "No hit needed; spirit and intellect first. With Selfless Healer mastery beats crit; with Eternal Flame crit is better, unless you are close to a haste breakpoint.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Holy Paladin guide, 2026/06/29 (Patch 5.5.4).",
      },
      Protection = {
        role = "TANK", primary = "Strength", attack = "melee",
        stats = { "Hit", "Expertise", "Mastery", "Stamina", "Haste", "Dodge", "Parry", "Strength" },
        notes = "Defensive order: hit to 7.5%, expertise to 15%, then mastery and stamina. For more damage, haste and crit move up right after the caps.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Protection Paladin guide, 2026/06/29 (Patch 5.5.4).",
      },
      Retribution = {
        role = "DAMAGER", primary = "Strength", attack = "melee",
        stats = { "Hit", "Expertise", "Haste", "Mastery", "Strength", "Crit" },
        notes = "Hit and expertise to 7.5% each - hit slightly first, since spells cannot be dodged. Haste beats mastery until 50% haste; past that, mastery is better.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Retribution Paladin guide, 2026/05/24 (Patch 5.5.4).",
      },
    },
  },
  HUNTER = {
    specOrder = { "Beast Mastery", "Marksmanship", "Survival" },
    specs = {
      ["Beast Mastery"] = {
        role = "DAMAGER", primary = "Agility", attack = "ranged",
        stats = { "Agility", "Hit", "Expertise", "Crit", "Haste", "Mastery" },
        notes = "Hit and expertise to 7.5% each, then crit and haste. As item level rises, mastery (your pet's damage) can pass haste.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Beast Mastery Hunter guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Marksmanship = {
        role = "DAMAGER", primary = "Agility", attack = "ranged",
        stats = { "Agility", "Hit", "Expertise", "Crit", "Haste", "Mastery" },
        notes = "Hit and expertise to 7.5% each, then crit and haste. As item level rises, mastery (Wild Quiver's extra shots) can pass haste.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Marksmanship Hunter guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Survival = {
        role = "DAMAGER", primary = "Agility", attack = "ranged",
        stats = { "Agility", "Hit", "Expertise", "Crit", "Haste", "Mastery" },
        notes = "Hit and expertise to 7.5% each, then crit and haste. Mastery is weakest on one target but strong in AoE, and can pass haste with better gear.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Survival Hunter guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
    },
  },
  ROGUE = {
    specOrder = { "Assassination", "Combat", "Subtlety" },
    specs = {
      Assassination = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Mastery", "Haste", "Crit" },
        notes = "Hit and expertise to 7.5% each; expertise matters a little less for you than for other melee, because of how poisons land. Crit is the weakest stat.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Assassination Rogue guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Combat = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Haste", "Mastery", "Crit" },
        notes = "Hit and expertise to 7.5% each, then haste and mastery - mastery's extra swings are as good in cleave as on one target.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Combat Rogue guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Subtlety = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Haste", "Crit", "Mastery" },
        notes = "Hit and expertise to 7.5% each, then haste and crit. Mastery is the weakest stat in the rotation.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Subtlety Rogue guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
    },
  },
  PRIEST = {
    specOrder = { "Discipline", "Holy", "Shadow" },
    specs = {
      Discipline = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Intellect", "Crit", "Spirit", "Mastery", "Haste" },
        notes = "No hit needed. Crit, spirit and mastery are close - more spirit when you are fresh at 90 or on mana-heavy fights. Haste is clearly last.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Discipline Priest guide, 2026/06/29 (Patch 5.5.4).",
      },
      Holy = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Intellect", "Spirit", "Crit", "Mastery", "Haste" },
        notes = "No hit needed. Crit just ahead of mastery, since crit works on every heal. Haste is low apart from breakpoints for extra heal-over-time ticks.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Holy Priest guide, 2026/06/29 (Patch 5.5.4).",
      },
      Shadow = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Spirit", "Expertise", "Haste", "Crit", "Mastery" },
        spiritIsHit = true,
        notes = "Hit to 15% - Spirit and expertise count toward it too. Then haste, crit and mastery; haste breakpoints for extra DoT ticks are worth looking up.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Shadow Priest guide, 2026/06/29 (Patch 5.5.4).",
      },
    },
  },
  DEATHKNIGHT = {
    specOrder = { "Blood", "Frost", "Unholy" },
    specs = {
      Blood = {
        role = "TANK", primary = "Strength", attack = "melee",
        stats = { "Hit", "Expertise", "Parry", "Dodge", "Haste", "Strength", "Stamina", "Crit", "Mastery" },
        notes = "Hit and expertise to 7.5% first, then parry and dodge. For more damage, crit and haste move up; for more safety, stamina and mastery do.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Blood Death Knight guide, 2026/06/29 (Patch 5.5.4).",
      },
      Frost = {
        role = "DAMAGER", primary = "Strength", attack = "melee",
        stats = { "Strength", "Hit", "Expertise", "Mastery", "Crit", "Haste" },
        notes = "Strength first at all times. Hit and expertise to 7.5% each, then mastery, crit and haste.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Frost Death Knight guide, 2026/06/29 (Patch 5.5.4).",
      },
      Unholy = {
        role = "DAMAGER", primary = "Strength", attack = "melee",
        stats = { "Strength", "Hit", "Expertise", "Crit", "Haste", "Mastery" },
        notes = "Strength first. Hit and expertise to 7.5% each; crit and haste both beat mastery, which is the weakest stat but still useful.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Unholy Death Knight guide, 2026/06/29 (Patch 5.5.4).",
      },
    },
  },
  SHAMAN = {
    specOrder = { "Elemental", "Enhancement", "Restoration" },
    specs = {
      Elemental = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Spirit", "Expertise", "Mastery", "Haste", "Crit" },
        spiritIsHit = true,
        notes = "Hit to 15% - Spirit and expertise count toward it too. Mastery and haste beat crit, because Lava Burst always crits anyway.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Elemental Shaman guide, 2026/06/29 (Patch 5.5.4).",
      },
      Enhancement = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Mastery", "Haste", "Crit" },
        notes = "Hit and expertise to 7.5% each - they do different jobs: one stops misses, the other dodges. Then mastery and haste; crit is lowest.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Enhancement Shaman guide, 2026/06/29 (Patch 5.5.4).",
      },
      Restoration = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Intellect", "Haste", "Crit", "Mastery", "Spirit" },
        notes = "No hit needed. Haste to a breakpoint for extra ticks rather than stacking it blindly. Spirit drops in value once your mana holds up.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Restoration Shaman guide, 2026/06/21 (Patch 5.5.4).",
      },
    },
  },
  MAGE = {
    specOrder = { "Arcane", "Fire", "Frost" },
    specs = {
      Arcane = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Mastery", "Haste", "Crit" },
        notes = "Hit to 15% - expertise counts toward it too. Then mastery and haste. Crit is the weakest stat; reforge it away where you can.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Arcane Mage guide, 2026-06-29 (Patch 5.5.4).",
      },
      Fire = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Crit", "Haste", "Mastery" },
        notes = "Hit to 15% - expertise counts toward it too. Crit is the best secondary because it also feeds Ignite; mastery is the weakest.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Fire Mage guide, 2026-06-29 (Patch 5.5.4).",
      },
      Frost = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Haste", "Crit", "Mastery" },
        notes = "Hit to 15% - expertise counts toward it too. Haste first; crit loses value as gear improves, and mastery overtakes it.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Frost Mage guide, 2026-06-29 (Patch 5.5.4).",
      },
    },
  },
  WARLOCK = {
    specOrder = { "Affliction", "Demonology", "Destruction" },
    specs = {
      Affliction = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Haste", "Mastery", "Crit" },
        notes = "Hit to 15% - expertise counts toward it too. Haste and mastery trade places around DoT-tick breakpoints; at high haste, mastery pulls ahead.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Affliction Warlock guide, 2026/06/29 (Patch 5.5.4).",
      },
      Demonology = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Haste", "Mastery", "Crit" },
        notes = "Hit to 15% - expertise counts toward it too. Then haste and mastery; haste breakpoints for Doom and Shadowflame are worth looking up.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Demonology Warlock guide, 2026/06/29 (Patch 5.5.4).",
      },
      Destruction = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Mastery", "Haste", "Crit" },
        notes = "Hit to 15% - expertise counts toward it too. Then mastery; haste and crit swap places depending on how close you are to a haste breakpoint.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Destruction Warlock guide, 2026/06/29 (Patch 5.5.4).",
      },
    },
  },
  MONK = {
    specOrder = { "Brewmaster", "Windwalker", "Mistweaver" },
    specs = {
      Brewmaster = {
        role = "TANK", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Haste", "Crit", "Mastery" },
        notes = "Agility, then hit and expertise, then haste and crit. For a more defensive setup, mastery moves up to right after the caps - it only strengthens Stagger.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Brewmaster Monk guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Windwalker = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Haste", "Crit", "Mastery" },
        notes = "Hit and expertise to 7.5% each, then haste, crit and mastery.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Windwalker Monk guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
      Mistweaver = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Intellect", "Spirit", "Haste", "Crit", "Mastery" },
        spiritIsHit = true,
        notes = "Spirit first: Stance of the Wise Serpent turns it into the hit and expertise your melee needs, so you rarely gear for them directly. Mastery is last.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Mistweaver Monk guide, 2026/06/29, Patch 5.5.4 (MoP Classic Phase 5).",
      },
    },
  },
  DRUID = {
    specOrder = { "Balance", "Feral", "Guardian", "Restoration" },
    specs = {
      Balance = {
        role = "DAMAGER", primary = "Intellect", attack = "spell",
        stats = { "Intellect", "Hit", "Haste", "Crit", "Mastery" },
        spiritIsHit = true,
        notes = "Hit to 15% - Spirit and expertise count toward it too. Haste beats crit until the haste soft cap, then crit is better. Mastery stays last.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Balance Druid guide, 2026/06/29 (Patch 5.5.4).",
      },
      Feral = {
        role = "DAMAGER", primary = "Agility", attack = "melee",
        stats = { "Agility", "Hit", "Expertise", "Mastery", "Crit", "Haste" },
        notes = "Hit and expertise to 7.5% each, then mastery: most of your damage is bleeds, and mastery makes them hit harder.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Feral Druid guide, 2026/06/29 (Patch 5.5.4).",
      },
      Guardian = {
        role = "TANK", primary = "Agility", attack = "melee",
        stats = { "Stamina", "Hit", "Expertise", "Crit", "Agility", "Haste", "Mastery" },
        notes = "Stamina first, then hit to 7.5% and expertise: 7.5% takes away a boss's dodge, 15% its parry too. Crit comes before agility and haste; mastery is last.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Guardian Druid guide, 2026/06/29 (Patch 5.5.4).",
      },
      Restoration = {
        role = "HEALER", primary = "Intellect", attack = nil,
        stats = { "Intellect", "Haste", "Spirit", "Mastery", "Crit" },
        notes = "No hit needed. Haste up to the breakpoint you are aiming for; past it, haste drops below spirit, mastery and crit.",
        source = "Stat priority: Wowhead's Mists of Pandaria Classic Restoration Druid guide, 2026/06/29 (Patch 5.5.4).",
      },
    },
  },
}
