# -*- coding: utf-8 -*-
"""Write StatCoachData_Forever.lua: which talent tree every Forever talent sits in (from the
harvested Icy Veins Forever talent calculator data, 21 Sep 2026), in the tree order Era's
tabSpec uses, plus the stat lists Forever's own guides give where Classic has none."""
import io
import json
import os

SRC = "C:/Users/Mel-g/CoachProbe/forever_talents"
OUT = "C:/Users/Mel-g/StatCoach/StatCoachData_Forever.lua"

# Era's tabSpec order per class, and how the harvest names those trees
TREES = {
    "WARRIOR": ["Arms", "Fury", "Protection"],
    "PALADIN": ["Holy", "Protection", "Retribution"],
    "HUNTER": ["Beast Mastery", "Marksmanship", "Survival"],
    "ROGUE": ["Assassination", "Combat", "Subtlety"],
    "PRIEST": ["Discipline", "Holy", "Shadow"],
    "SHAMAN": ["Elemental Combat", "Enhancement", "Restoration"],
    "MAGE": ["Arcane", "Fire", "Frost"],
    "WARLOCK": ["Affliction", "Demonology", "Destruction"],
    "DRUID": ["Balance", "Feral Combat", "Restoration"],
}


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = []
out.append('''--[[ StatCoachData_Forever.lua
     WORLD OF WARCRAFT: FOREVER data. Loaded only by the Forever TOC. Pure tables.

     Forever has one specialization per class (all named after the class, read off the beta,
     build 69977) and its three classic talent trees live inside ONE trait tree, so the game
     cannot be asked which tree you play. StatCoach counts your points per tree instead, by
     talent name. Which tree a talent sits in comes from Icy Veins' Forever talent calculator
     data (harvested 21 Sep 2026, every class complete); the order of the trees is Era's
     (StatCoachData_Era.lua tabSpec), so tree 1 of a paladin is Holy everywhere.

     Generated by gen_forever_data.py - edit the generator, not this file.
]]--

local ADDON, ns = ...
ns.Data = ns.Data or {}
local D = ns.Data

D.forever = D.forever or {}
local F = D.forever

-- [CLASS] = { [talent name] = tree (1, 2 or 3) }
F.talentTree = {''')

total = 0
for cls in ["WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE", "WARLOCK", "DRUID"]:
    d = json.load(io.open(os.path.join(SRC, cls.lower() + ".json"), encoding="utf-8"))
    order = TREES[cls]
    seen = {}
    for t in d["talents"]:
        tree = t["tree"]
        assert tree in order, (cls, tree)
        name = t["name"].strip()
        idx = order.index(tree) + 1
        if name in seen and seen[name] != idx:
            raise SystemExit("talent in two trees: %s %s" % (cls, name))
        seen[name] = idx
    total += len(seen)
    out.append("  %s = {" % cls)
    for name in sorted(seen):
        out.append("    [%s] = %d," % (lua_str(name), seen[name]))
    out.append("  },")
out.append("}")

out.append('''
-- Stat lists from Forever's own guides, used where Classic has none. Same shape as Era's
-- spec entries; only the fields given here replace Era's.
F.specs = {
  PALADIN = {
    Protection = {
      stats = { "Hit", "Stamina", "Strength", "Armor", "Agility", "Crit" },
      notes = "Weapon damage first while leveling, then hit, then stamina - Icy Veins' Forever tank guide. Strength adds damage, not survival.",
      source = "Stat priority: Icy Veins' WoW Forever Protection Paladin guide, 17 Sep 2026 (no Classic guide has one).",
    },
  },
}
''')

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("wrote %s: %d talents" % (OUT, total))
